apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-ext
  labels:
    app: {{ .Chart.Name }}-ext
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Chart.Name }}

