apiVersion: v2
name: devops-poc
version: 0.1.0
description: A Helm chart for the webapidemo application

type: application

# This is the default Kubernetes version used by the chart
kubeVersion: ">= 1.20.0"